### ISSUE TITLE
No release version

### ISSUE THREAD

**Issue by ajaxStardust** [lionello/terminal-open-with#1]
cant install extension : VS Code reports "No Release Version"
[screenshot
](https://i.imgur.com/8hYkh4X/)

**Comment by lionello** [comment]
Thanks for raising the issue. I've published v0.1.1 just now (no changes compared to 0.2.0)

Install from https://marketplace.visualstudio.com/items?itemName=lionello.terminal-open-with

**Comment by ajaxStardust** [comment]
thank you!
WordpressCenter.net <https://www.wordpresscenter.net/> 
@ajaxStardust
-------- Original Message --------
Subject: Re: [lionello/terminal-open-with] No release version (Issue #1)
Date: Sun Apr 09 2023 19:03:52 GMT-0400 (Eastern Daylight Time)
From: "Lio李歐" ***@***.***>
To: "lionello/terminal-open-with" ***@***.***>
CC: "ajaxStardust" ***@***.***>, "Author" ***@***.***>
Thanks for raising the issue. I've published v0.1.1 just now (no changes compared to 0.2.0)
Install from https://marketplace.visualstudio.com/items?itemName=lionello.terminal-open-with <https://marketplace.visualstudio.com/items?itemName=lionello.terminal-open-with>
